name: elegant
dependencies:
- python=3.5*
- numpy=1.10*
- matplotlib=1.5*
- astropy=1.1*
- pandas=0.17*
- scipy=0.16*
- scikit-learn=0.17*
- scikit-image=0.11*
- networkx=1.10*
- xlrd=0.9*
- jupyter=1.0*
- sympy=0.7*
- toolz=0.7*
- six=1.10*
- pip:
  # Seaborn is available on conda but not for Py3.5, so use pip
  - seaborn==0.5
  - notedown==1.5
