name: elegant
channels:
- conda-forge
dependencies:
- python=3.6*
- numpy=1.12*
- matplotlib=2.0*
- pandas=0.19*
- scipy=0.19*
- scikit-learn=0.18*
- scikit-image=0.13*
- xlrd=1.0*
- jupyter=1.0*
- sympy=1.*
- toolz=0.8*
- six=1.10*
- beautifulsoup4=4.5*
- pillow
- lxml
- networkx  # make sure nx installed even if no git
- pip:
  # not available on conda, so use pip
  - notedown>=1.5
  - jupytercontrib>=0.0.5
  - bs4
  # need improvements from master branch
  - git+https://github.com/networkx/networkx.git
